#ifndef __COMPONENTS_INC_HEADER_GUARD__
#define __COMPONENTS_INC_HEADER_GUARD__

#include <iostream> // std::cout, std::cerr, std::cin
#include <fstream> // std::ofstream, std::ifstream
#include <string> // std::string, std::getline
#include <cstdlib> // free
#include <unordered_map> // std::unordered_map
#include <scbl.hh> // SCBL::Interpreter, SCBL::Exception, SCBL::word,
                   // SCBL::i8, SCBL::i16, SCBL::i32, SCBL::i64,
                   // SCBL::ui8, SCBL::ui16, SCBL::ui32, SCBL::ui64

#endif // __COMPONENTS_INC_HEADER_GUARD__
